# Generated by Django 4.2.21 on 2025-07-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easySIPp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uacappconfig',
            name='protocol_uac',
            field=models.CharField(choices=[('u1', 'UDP'), ('t1', 'TCP')], default='u1', max_length=10),
        ),
        migrations.AlterField(
            model_name='uasappconfig',
            name='protocol_uas',
            field=models.CharField(choices=[('u1', 'UDP'), ('t1', 'TCP')], default='u1', max_length=10),
        ),
    ]
